version: "3"
name: shortlink-app
services:
  mysql:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: "shortlink_db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - shortlink-mysql-data:/var/lib/mysql
    networks:
      - main_network
  backend:
    container_name: shortlink_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: shortlink_db
    depends_on:
      - mysql
    command: npm run start:dev
    networks:
      - main_network
  frontend:
    container_name: shortlink_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - main_network
  adminer:
    container_name: database_manager
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - main_network
volumes:
  shortlink-mysql-data:
networks:
  main_network:
    driver: bridge